version: "3"

services:
  tp1:
    container_name: tp1
    image: aqtiongame/server:v11  # replace_with_image_reference_from_readme
    ports:  # ports to map to host, cannot be in use and must correspond to same value as PORTS variable in .env
      - "27910:27910/udp"
      - "27910:27910/tcp"
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - ./tp1.env  # set server parameter in env_file
    environment:
      - TZ=Australia/Melbourne # set your local timezone
    volumes:
      - /<host_path_to_aqtion_demos>:/aq2server/action/demos
      - /<host_path_to_aqtion_logs>:/aq2server/action/logs
      - ./tp1.motd:/aq2server/action/motd.txt:ro
      - maps:/aq2server/action/maps

volumes:
  maps:
